# name: E2E (N3)
# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "0 6 * * *"

# jobs:
#   e2e:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: ./.github/actions/preparar-python
#       - run: make test-e2e
